/*
* EPOS_command_send.h
*
* Created on: 17.01.2018
* Author: Meiers, Peter; Kimmer, Kevin
* Company: Hochschule Trier
*/

#ifndef UC_EPOS_COMMAND_SEND_H_
#define UC_EPOS_COMMAND_SEND_H_

// SDO-Byte
#define WRITING_SEND 0x22
#define WRITING_REVEIVE 0x60
#define READING_SEND 0x40
#define READING_RECEIVE_1BYTE 0x4F
#define READING_RECEIVE_2BYTE 0x4B
#define READING_RECEIVE_4BYTE 0x4B
//Error
#define ERROR_REGISTER 0x1001
#define NUMBER_OF_ERRORS 0x1003
#define ERROR_HISTORY_1 0x1
#define ERROR_HISTORY_2 0x2
#define ERROR_HISTORY_3 0x3
#define ERROR_HISTORY_4 0x4
#define ERROR_HISTORY_5 0x5
// Objects
#define CONTROL_WORD 0x6040
#define STATUS_WORD 0x6041
#define MODES_OF_OPERATION 0x6060
#define MODES_OF_OPERATION_DISPLAY 0x6061
//#define CAN_BITRATE 0x2001
#define MAX_FOLLOWING_ERROR 0x6065
#define CURRENT_REGULATOR 0x60F6
#define SPEED_REGULATOR 0x60F9
#define POSITION_REGULATOR 0x60FB
#define ENCODER_COUNTER 0x2020
#define ENCODER_COUNTER_INDEX_PULSE 0x2021
#define HALLSENSOR_PATTERN 0x2022
#define CURRENT_ACTUAL_VALUE_AVERAGED 0x2027
#define VELOCITY_ACTUAL_VALUE_AVERAGED 0x2028
#define CURRENT_MODE_SETTING_VALUE 0x2030
#define FOLLOWING_ERROR_ACTUAL_VALUE 0x20F4
#define POSITION_DEMAND_VALUE 0x6062
#define POSITION_ACTUAL_VALUE 0x6064
#define VELOCITY_DEMAND_VALUE 0x606B
#define VELOCITY_ACTUAL_VALUE 0x606C
#define CURRENT_ACTUAL_VALUE 0x6078

//SUB_INDEX
#define P_GAIN 0x1
#define I_GAIN 0x2
#define D_GAIN 0x3
#define VELOCITY_FEEDFORWARD_FACTOR 0x4
#define ACCELERATION_FEEDFORWARD_FACTOR 0x5
//STATUS_CONTROLWORD
#define SHUTDOWN 0x6


#define SWITCH_ON 0x7
#define DISABLE_VOLTAGE 0x0
#define QUICK_STOP 0x2
#define DISABLE_OPERATION 0x7
#define ENABLE_OPERATION 0xF
#define FAULT_RESET 0x80

//STATUS_MODESOFOPERATION
#define ELECTRICAL_GEARING 0xF7
#define JOGGING 0xF8
#define HOMING 0xF9
#define TRAJECTORY 0xFA
#define ANALOG_CURRENT 0xFB
#define ANALOG_SPEED 0xFC
#define DIGITAL_CURRENT 0xFD
#define DIGITAL_SPEED 0xFE
#define POSITION 0xFF
#define POSITIONING_PP 0x1
#define SPEED_VL 0x2
#define SPEED_PV 0x3
#define TORQUE_TQ 0x4
#define HOMING_HM 0x6
#define INTERPOLATION 0x7

#endif /* UC_EPOS_COMMAND_SEND_H_ */
// End of file.
